# **Binary Text Classification - RNN project**

# 1. Load libraries and frameworks

In [1]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Model
from tensorflow.keras.layers import Input, Embedding, SimpleRNN, Dense

# 2. Dataset

In [2]:
# Input
sentences = [
    "I love this product",
    "This movie made me smile",
    "Service was friendly and quick",
    "Today felt bright and happy",
    "This is the best day",
    "Absolutely fantastic experience",
    "I enjoyed every single moment",
    "Great job, well done",
    "The food tasted delicious",
    "Totally recommend to everyone",
    "Very satisfied with results",
    "This worked better than expected",
    "Amazing quality and value",
    "Such a pleasant surprise",
    "I feel positive about this",
    "I hate this product",
    "This movie bored me",
    "Service was rude and slow",
    "Today was cold and lonely",
    "This is the worst day",
    "Terrible experience overall",
    "I regret buying this",
    "Very disappointed with results",
    "The food tasted awful",
    "Do not recommend this",
    "It broke after one use",
    "Not worth the money",
    "Utterly frustrating and annoying",
    "I feel negative about this",
    "Such a waste of time"
]

# Target
labels = [1] * 15  +  [0] * 15
labels = np.array(labels)

# 3. Text pre-processing

In [3]:
vocab_size = 2000      # maximum number of words to keep in vocabulary

tokenizer = Tokenizer(num_words = vocab_size, oov_token = "<OOV>")      # create a tokenizer; unknown words will be represented as <OOV>
tokenizer.fit_on_texts(sentences)      # learn the vocabulary from "sentences" and assing an integer ID to each word

seqs = tokenizer.texts_to_sequences(sentences)    # convert each sentence from words into a sequence of integer IDs

maxlength = max(len(s) for s in seqs)      # find length of the longest sequence
X = pad_sequences(seqs, maxlen = maxlength, padding = "post")     # pad shorter sequences with 0s at the end so that all have the same length

y = labels        # store target / output labels in "y"

In [4]:
maxlength

5

In [5]:
tokenizer.word_index

{'<OOV>': 1,
 'this': 2,
 'i': 3,
 'and': 4,
 'the': 5,
 'was': 6,
 'product': 7,
 'movie': 8,
 'me': 9,
 'service': 10,
 'today': 11,
 'is': 12,
 'day': 13,
 'experience': 14,
 'food': 15,
 'tasted': 16,
 'recommend': 17,
 'very': 18,
 'with': 19,
 'results': 20,
 'such': 21,
 'a': 22,
 'feel': 23,
 'about': 24,
 'not': 25,
 'love': 26,
 'made': 27,
 'smile': 28,
 'friendly': 29,
 'quick': 30,
 'felt': 31,
 'bright': 32,
 'happy': 33,
 'best': 34,
 'absolutely': 35,
 'fantastic': 36,
 'enjoyed': 37,
 'every': 38,
 'single': 39,
 'moment': 40,
 'great': 41,
 'job': 42,
 'well': 43,
 'done': 44,
 'delicious': 45,
 'totally': 46,
 'to': 47,
 'everyone': 48,
 'satisfied': 49,
 'worked': 50,
 'better': 51,
 'than': 52,
 'expected': 53,
 'amazing': 54,
 'quality': 55,
 'value': 56,
 'pleasant': 57,
 'surprise': 58,
 'positive': 59,
 'hate': 60,
 'bored': 61,
 'rude': 62,
 'slow': 63,
 'cold': 64,
 'lonely': 65,
 'worst': 66,
 'terrible': 67,
 'overall': 68,
 'regret': 69,
 'buying': 70,
 'd

In [6]:
seqs

[[3, 26, 2, 7],
 [2, 8, 27, 9, 28],
 [10, 6, 29, 4, 30],
 [11, 31, 32, 4, 33],
 [2, 12, 5, 34, 13],
 [35, 36, 14],
 [3, 37, 38, 39, 40],
 [41, 42, 43, 44],
 [5, 15, 16, 45],
 [46, 17, 47, 48],
 [18, 49, 19, 20],
 [2, 50, 51, 52, 53],
 [54, 55, 4, 56],
 [21, 22, 57, 58],
 [3, 23, 59, 24, 2],
 [3, 60, 2, 7],
 [2, 8, 61, 9],
 [10, 6, 62, 4, 63],
 [11, 6, 64, 4, 65],
 [2, 12, 5, 66, 13],
 [67, 14, 68],
 [3, 69, 70, 2],
 [18, 71, 19, 20],
 [5, 15, 16, 72],
 [73, 25, 17, 2],
 [74, 75, 76, 77, 78],
 [25, 79, 5, 80],
 [81, 82, 4, 83],
 [3, 23, 84, 24, 2],
 [21, 22, 85, 86, 87]]

In [7]:
X[0]         # "I love this product"

array([ 3, 26,  2,  7,  0], dtype=int32)

In [8]:
X[29]        # "Such a waste of time"

array([21, 22, 85, 86, 87], dtype=int32)

# 4. RNN model

In [9]:
embed_dimension = 16
rnn_units = 8

In [10]:
inp = Input(shape = (maxlength,), dtype = "int32", name = "input")
x = Embedding(input_dim = vocab_size, output_dim = embed_dimension, mask_zero = True, name = "embed")(inp)

rnn = SimpleRNN(units = rnn_units, return_sequences = False, return_state = False, name = "simple_rnn")
x_last = rnn(x)
out = Dense(1, activation = "sigmoid", name = "out")(x_last)
model = Model(inputs = inp, outputs = out)
model.compile(optimizer = "adam", loss = "binary_crossentropy", metrics = ["accuracy"])
model.summary()

2026-08-13 18:38:48.643510: E external/local_xla/xla/stream_executor/cuda/cuda_platform.cc:51] failed call to cuInit: INTERNAL: CUDA error: Failed call to cuInit: UNKNOWN ERROR (303)


Model: "functional"

┏━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━┓
┃ Layer (type)        ┃ Output Shape      ┃    Param # ┃ Connected to      ┃
┡━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━┩
│ input (InputLayer)  │ (None, 5)         │          0 │ -                 │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ embed (Embedding)   │ (None, 5, 16)     │     32,000 │ input[0][0]       │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ not_equal           │ (None, 5)         │          0 │ input[0][0]       │
│ (NotEqual)          │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ simple_rnn          │ (None, 8)         │        200 │ embed[0][0],      │
│ (SimpleRNN)         │                   │            │ not_equal[0][0]   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ out (Dense)         │ (None, 1)         │          9 │ simple_rnn[0][0]  │
└─────────────────────┴───────────────────┴────────────┴───────────────────┘

 Total params: 32,209 (125.82 KB)

 Trainable params: 32,209 (125.82 KB)

 Non-trainable params: 0 (0.00 B)

In [11]:
# training
model.fit(X, y, epochs = 25, batch_size = 8, verbose = 1)

Epoch 1/25
4/4 ━━━━━━━━━━━━━━━━━━━━ 2s 12ms/step - accuracy: 0.4333 - loss: 0.7049
Epoch 2/25
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.5667 - loss: 0.6871
Epoch 3/25
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7667 - loss: 0.6722
Epoch 4/25
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8000 - loss: 0.6580
Epoch 5/25
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8000 - loss: 0.6433
Epoch 6/25
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8667 - loss: 0.6293
Epoch 7/25
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.9000 - loss: 0.6138
Epoch 8/25
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.9333 - loss: 0.5988
Epoch 9/25
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.9333 - loss: 0.5810
Epoch 10/25
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.9667 - loss: 0.5641
Epoch 11/25
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.9667 - loss: 0.5455
Epoch 12/25
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.9667 - loss: 0.5263
E

# 5. Task

Create an intermediate Keras model to visualize the outputs of the embedding layer and the hidden states of the SimpleRNN layer from the existing model. Then, use this intermediate model to predict on the input data and visualize the outputs

## Create intermediate model

### Subtask:

Build a new Keras Model that takes the same input as the original model but outputs the embedding layer and the hidden states of the SimpleRNN layer.

### Reasoning: 

Define an intermediate Keras model with the same input as the original model and outputs from the embedding and simple RNN layers.

In [12]:
intermediate_model = Model(inputs=model.inputs, outputs=[model.get_layer('embed').output, model.get_layer('simple_rnn').output])

In [13]:
from tensorflow.keras.layers import SimpleRNN as SRNN
seq_inp = Input(shape=(maxlength,), dtype='int32')
seq_emb = model.get_layer('embed')(seq_inp)  # reuse trained embedding

# Create RNN with return_sequences=True
rnn_seq = SRNN(units=rnn_units, return_sequences=True, name='rnn_seq')

# DO NOT CALL build() manually
seq_hidden = rnn_seq(seq_emb)  # builds automatically

# Copy trained RNN weights
try:
    trained_weights = model.get_layer('simple_rnn').get_weights()
    rnn_seq.set_weights(trained_weights)
    print("Copied RNN weights into sequence-inspection RNN.")
except Exception as e:
    print("Could not copy weights automatically:", e)

inspect_model = Model(inputs=seq_inp, outputs=seq_hidden)

# Inspect
idx = 0
example_seq = X[idx:idx+1]  # shape (1, maxlength)
hidden_seq = inspect_model.predict(example_seq)

print("Sentence:", sentences[idx])
print("Token ids:", example_seq)
print("Hidden states per timestep shape:", hidden_seq.shape)
print("Hidden states (timesteps x units):")
print(np.round(hidden_seq[0], 3))

Copied RNN weights into sequence-inspection RNN.
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 203ms/step
Sentence: I love this product
Token ids: [[ 3 26  2  7  0]]
Hidden states per timestep shape: (1, 5, 8)
Hidden states (timesteps x units):
[[ 0.05   0.025  0.062 -0.041  0.083 -0.099  0.074 -0.026]
 [ 0.11  -0.008  0.013  0.319 -0.095 -0.006  0.076  0.215]
 [-0.036  0.139 -0.164  0.013 -0.298  0.302 -0.156  0.192]
 [-0.403 -0.212 -0.131  0.298  0.326 -0.068 -0.117 -0.058]
 [-0.403 -0.212 -0.131  0.298  0.326 -0.068 -0.117 -0.058]]
